import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1400, height: 860 } })
p.on('pageerror', e => console.log('PAGEERROR', e.message))
p.on('console', m => { if (m.type()==='error') console.log('CONSOLE', m.text().slice(0,140)) })
await p.goto('http://localhost:5240/', { waitUntil: 'networkidle' })
await p.waitForTimeout(1000)
await p.getByRole('button', { name: 'СТАРТ' }).click()
await p.waitForTimeout(1000)
await p.keyboard.press('KeyG')
await p.waitForTimeout(1200)
for (let x = 376; x < 396; x += 2) for (const y of [574,580,586]) { await p.mouse.move(x,y); await p.waitForTimeout(30) }
await p.mouse.click(385, 580)
await p.waitForTimeout(400)
await p.screenshot({ path: 'apps/web/_panel.png' })
const btn = p.getByRole('button', { name: 'ПРЫЖОК' })
console.log('кнопка прыжка:', await btn.count(), 'активна:', await btn.isEnabled().catch(()=>'нет'))
await btn.click()
await p.waitForTimeout(2500)
await p.screenshot({ path: 'apps/web/_after.png' })
console.log('после прыжка: карта закрыта =', (await p.getByRole('button', { name: 'G — ЗАКРЫТЬ' }).count()) === 0)
await b.close()
